start: section+
section: header operation+
header: "[" PATH "#" TAG "]" LF
PATH: /[^#\]\n]+/
TAG: /[0-9A-Z]{4}/
operation: put | cut | ins | app | rem | move
put: "PUT " RANGE ":" LF add_line*
cut: "CUT " RANGE LF
ins: "INS " ADDRESS ":" LF add_line*
app: "APP " ADDRESS ":" LF add_line*
rem: "REM" LF
move: "MOV " PATH LF
RANGE: /[^:\n]+/
ADDRESS: /[^:\n]+/
add_line: "+" /[^\n]*/ LF
%import common.LF
