//! Conservative endpoint classification and probe scheduling.

use std::{net::IpAddr, time::Duration};

use omp_core::Str;
use serde::{Deserialize, Serialize};
use strum::{Display, EnumString, IntoStaticStr};

/// Supported local or configured OpenAI-compatible endpoint families.
#[derive(
	Clone, Copy, Debug, Display, EnumString, Eq, IntoStaticStr, PartialEq, Serialize, Deserialize,
)]
#[serde(rename_all = "kebab-case")]
#[strum(serialize_all = "kebab-case", ascii_case_insensitive)]
pub enum DiscoveryEndpointKind {
	/// Ollama tags and show APIs.
	Ollama,
	/// llama.cpp models and props APIs.
	LlamaCpp,
	/// LM Studio's v0 model API.
	LmStudio,
	/// LiteLLM proxy model API.
	LiteLlm,
	/// Generic OpenAI-compatible model API.
	OpenAi,
}

/// Why an endpoint may be probed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum EndpointOrigin {
	/// Built-in known-loopback default.
	KnownLoopback,
	/// Explicit settings or environment configuration.
	Configured,
}

/// One typed discovery endpoint and its deadline class.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryEndpoint {
	/// Expected endpoint family.
	pub kind:     DiscoveryEndpointKind,
	/// Base URL.
	pub base_url: Str,
	/// Whether the endpoint was auto-known or explicitly configured.
	pub origin:   EndpointOrigin,
}

impl DiscoveryEndpoint {
	/// Returns the complete-request deadline for this endpoint.
	pub fn deadline(&self) -> Duration {
		if self.is_loopback() {
			Duration::from_millis(900)
		} else {
			Duration::from_secs(6)
		}
	}

	/// Reports whether the configured host is an IP loopback or `localhost`.
	pub fn is_loopback(&self) -> bool {
		url::Url::parse(self.base_url.as_str())
			.ok()
			.and_then(|url| url.host_str().map(str::to_owned))
			.is_some_and(|host| {
				host.eq_ignore_ascii_case("localhost")
					|| host
						.parse::<IpAddr>()
						.is_ok_and(|address| address.is_loopback())
			})
	}
}

/// Returns the only endpoints eligible for unconfigured automatic probing.
pub fn known_loopback_endpoints() -> Box<[DiscoveryEndpoint]> {
	Box::new([
		DiscoveryEndpoint {
			kind:     DiscoveryEndpointKind::Ollama,
			base_url: Str::new_static("http://127.0.0.1:11434"),
			origin:   EndpointOrigin::KnownLoopback,
		},
		DiscoveryEndpoint {
			kind:     DiscoveryEndpointKind::LlamaCpp,
			base_url: Str::new_static("http://127.0.0.1:8080"),
			origin:   EndpointOrigin::KnownLoopback,
		},
		DiscoveryEndpoint {
			kind:     DiscoveryEndpointKind::LmStudio,
			base_url: Str::new_static("http://127.0.0.1:1234"),
			origin:   EndpointOrigin::KnownLoopback,
		},
	])
}

/// Converts a base-URL setting or environment override into explicit
/// configuration.
///
/// Remote and LAN URLs are accepted only through this function; they are never
/// generated by [`known_loopback_endpoints`].
pub fn configured_endpoint(
	kind: DiscoveryEndpointKind,
	base_url: &str,
) -> Result<DiscoveryEndpoint, EndpointError> {
	let parsed = url::Url::parse(base_url).map_err(|_| EndpointError::InvalidUrl)?;
	if !matches!(parsed.scheme(), "http" | "https") || parsed.host_str().is_none() {
		return Err(EndpointError::InvalidUrl);
	}
	Ok(DiscoveryEndpoint {
		kind,
		base_url: Str::new(base_url.trim_end_matches('/')),
		origin: EndpointOrigin::Configured,
	})
}

/// Detects likely proxy families without turning detection into authority.
pub fn supported_endpoint_types(base_url: &str) -> Box<[DiscoveryEndpointKind]> {
	let lower = base_url.to_ascii_lowercase();
	if lower.contains("11434") || lower.contains("ollama") {
		Box::new([DiscoveryEndpointKind::Ollama, DiscoveryEndpointKind::OpenAi])
	} else if lower.contains("1234") || lower.contains("lmstudio") || lower.contains("lm-studio") {
		Box::new([DiscoveryEndpointKind::LmStudio, DiscoveryEndpointKind::OpenAi])
	} else if lower.contains("litellm") || lower.contains("4000") {
		Box::new([DiscoveryEndpointKind::LiteLlm, DiscoveryEndpointKind::OpenAi])
	} else if lower.contains("8080") || lower.contains("llama") {
		Box::new([DiscoveryEndpointKind::LlamaCpp, DiscoveryEndpointKind::OpenAi])
	} else {
		Box::new([DiscoveryEndpointKind::OpenAi])
	}
}

/// Invalid configured endpoint.
#[derive(Clone, Copy, Debug, thiserror::Error, Eq, PartialEq)]
pub enum EndpointError {
	/// The URL is not an absolute HTTP(S) endpoint.
	#[error("configured discovery endpoint must be an absolute HTTP(S) URL")]
	InvalidUrl,
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn automatic_endpoints_are_loopback_only_and_remote_is_explicit() {
		assert!(
			known_loopback_endpoints()
				.iter()
				.all(DiscoveryEndpoint::is_loopback)
		);
		let remote = configured_endpoint(DiscoveryEndpointKind::OpenAi, "https://models.example/v1")
			.expect("configured remote");
		assert_eq!(remote.origin, EndpointOrigin::Configured);
		assert!(!remote.is_loopback());
		assert!(remote.deadline() > known_loopback_endpoints()[0].deadline());
	}
}
